# MBX and SCME/f are external and require compiling.
# Ignore them since we can't test them in GitHub actions.
ignore:
  - src/md/potentials/MBX.jl
  - src/md/potentials/SCMEf.jl
  - src/md/potentials/funcs/TTMnrg.jl
  - src/lib/MBX
  - src/lib/SCMEf
  - src/lib/Phonopy
